name: Commit Action Demo
on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout repository
         uses: actions/checkout@v2

       -  name: Print message
          run: echo "my first workflow"
         
     
